### ISSUE TITLE
Feature Request : Deleting user reviews or Blocking someone from reviewing you

### ISSUE THREAD

**Issue by lera2od** [StupidityDB/Server#2]
I have some drama going around with some people and today I saw that they left stupid reviews on my account. A way to block certain people from reviewing you would be pretty nice. 
https://imgur.com/SR2Rjrh
(The last guy called me a fucking terorist organization leader)

**Comment by mantikafasi** [comment]
You can opt out from website. this will disable reviews on your profile but you wont able to review anyone

**Comment by lera2od** [comment]
But still this is a pretty bad way of handling a situation like this.

**Comment by mantikafasi** [comment]
as long as they dont break reviewdb rules I cant do anything about it.

**Comment by 00unkn0wn00** [comment]
that breaks the laws though he can get arrested for that. more info about the [PKK Terrorist Organization Leader](https://en.wikipedia.org/wiki/Abdullah_%C3%96calan)

**Comment by mantikafasi** [comment]
this issue is already solved since we allowed people to delete reviews from their own profile and block people
